# develop by taha-gouyandeh
version: '2.2'
services:
  mysql:
    container_name: mysql
    image: mysql:8.1.0
    restart: always
    environment:
      MYSQL_DATABASE: chat-db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - mysql-data:/var/lib/mysql

#  nestjs-app:
#    container_name: chat-db-backend
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    depends_on:
#      - mysql
#    environment:
#      MYSQL_HOST: mysql
#      MYSQL_PORT: 3306
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#      MYSQL_DATABASE: chat-db
#    volumes:
#      - app-data:/app
#    networks:
#      - mynetwork

volumes:
  mysql-data:
  app-data:

networks:
  mynetwork:

